### ISSUE TITLE
Create tags to play nice when bringing in through composer

### ISSUE THREAD

**Issue by xaviered** [quipo/kafka-php#18]
There are no tags in the repo. Would be nice to have tags for maintaining different version instead of just `dev-master`.

Here some helpful links on how to do this just in case.
https://help.github.com/articles/creating-releases/
https://stackoverflow.com/questions/18216991/create-a-tag-in-github-repository

Thank you.

**Comment by xaviered** [comment]
@quipo 🔝

**Comment by quipo** [comment]
done, thanks

**Comment by xaviered** [comment]
thank you!

**Comment by xaviered** [comment]
Any way you can update it on packagist too? It's only showing `dev-master` as of now.
https://packagist.org/packages/quipo/kafka-php

**Comment by xaviered** [comment]
@quipo 🔝

**Comment by quipo** [comment]
@xaviered  I've never used Packagist... I created an account and linked my GitHub profile, not sure how to claim the package, or how to update it?

**Comment by xaviered** [comment]
Oh I see. Looks like someone else added your repo to packagist
https://packagist.org/users/sunsky/

I'll see if they can update it. It should be as simple as pressing a UI update button.

Thanks for your help on this.

**Comment by xaviered** [comment]
@quipo Looks like the tag needs to be in the form of `X.Y.Z` or `vX.Y.Z`
https://packagist.org/about

Also, on on that page, it shows you how to setup a GitHub hook so that it automatically sends any updates to Packagist. I don't know who that `Sunsky` user is, but I'm pretty sure you can get maintainer access since you own the repo. 

Furthermore, if you get maintainer access, you'll get an API_TOKEN and you can manually trigger an update with a POST request. Here is a CURL sample
```
curl -XPOST \
  -H'content-type:application/json' \
  -d'{"repository":{"url":"https://packagist.org/packages/quipo/kafka-php"}}' \
  'https://packagist.org/api/update-package?username=USERNAME&apiToken=API_TOKEN'

```
https://packagist.org/about#how-to-update-packages

Thanks in advance.

**Comment by xaviered** [comment]
@quipo I have reached out to the user that created the package in the first place. They have released the package and I have registered it now. Please let me know if you want me to release it so you can handle it. Thank you.

https://packagist.org/packages/quipo/kafka-php

**Comment by quipo** [comment]
oh thanks. Yes, please go ahead and add the release to the Packagist page.   I've tagged v1.0.0  btw, so it's compatible.  Happy to manage it after that.  Thanks for your help!

**Comment by xaviered** [comment]
Great. I'm going to abandon the package so you can pick it up. I think if you setup the GitHub hook, it will automatically update whenever you make changes to your repo.
https://packagist.org/about#how-to-update-packages

Thanks for all your help.

**Comment by xaviered** [comment]
@quipo I just abandoned the package. Please claim it at https://packagist.org/packages/submit ... you'll have to login with your packagist account.

**Comment by xaviered** [comment]
👍 thanks!
