### ISSUE TITLE
fwrite may cause E_NOTICE but otherwise the program is fine

### ISSUE THREAD

**Issue by michaelbutler** [quipo/kafka-php#19]
We have noticed in our environment with PHP 7.2 and Kafka 0.7, this fwrite can cause E_NOTICEs to occur: https://github.com/quipo/kafka-php/blob/master/src/lib/Kafka/Socket.php#L256

Example: `fwrite(): send of 3895 bytes failed with errno=32 Broken pipe`

Looking through the PHP source code I couldn't exactly find why this is. In any case, if `fwrite` causes an E_NOTICE, it will still continue to line 257 and check the return value, throwing an exception if `-1` or `false` but otherwise continuing (perhaps 0 was returned). We don't seem to be getting the `Kafka_Exception_Socket` nor the `Kafka_Exception_Socket_Timeout` so I'm thinking we might be able to squelch this one.

Maybe this library should wrap the `fwrite` call with `set_error_handler` and `restore_error_handler` in order to capture these non fatal warnings?

**Comment by michaelbutler** [comment]
Also, speaking of that, let's say `fwrite` did return `0`. Is an infinite loop possible? perhaps `stream_select` returned success so it would seem like it is writeable, however `fwrite` could fail every time with 0, causing this loop to spin infinitely?
I could try forking temporarily and augmenting the code to see if this indeed is happening.

**Comment by michaelbutler** [comment]
Fix provided in https://github.com/quipo/kafka-php/pull/20

**Comment by quipo** [comment]
Thanks for the patch
